Update action.yaml

diff --git a/image-deployment/actions/promotion-inputvalidation/action.yaml b/image-deployment/actions/promotion-inputvalidation/action.yaml
--- a/image-deployment/actions/promotion-inputvalidation/action.yaml
+++ b/image-deployment/actions/promotion-inputvalidation/action.yaml
@@ -33,30 +33,34 @@ runs:
         valid_platform=(aws azure all)
         valid_env_pair=(dev-int int-stage stage-preprod spro-preprod)
         
+   #-----------------------------------------Checking  source_env--------------------------------------------------          
         if [[ ! (" ${valid_src_env[*]} " =~ " ${{inputs.source_env}} ") ]]
         then
           echo "Provide the proper environment listed here [ ${valid_src_env[*]} ] for source env" 
           exit 1
         fi 
-        
+  #-----------------------------------------Checking ptarget_env--------------------------------------------------           
         if [[ ! (" ${valid_target_env[*]} " =~ " ${{inputs.target_env}} ") ]]
         then
           echo "Provide the proper environment listed here [ ${valid_target_env[*]} ] for target " 
           exit 1
         fi
-        
+  #-----------------------------------------Checking source and target pair --------------------------------------------------           
         if [[ !(" ${valid_env_pair[*]} " =~ " ${{ inputs.source_env }}-${{ inputs.target_env }} ") ]]
         then
           echo "Cannot Promote Images from ${{ inputs.source_env }} to ${{ inputs.target_env }}"
           exit 1
         fi
-        
+  #-----------------------------------------Checking platform --------------------------------------------------        
+  
         if [[ ! (" ${valid_platform[*]} " =~ " ${{inputs.platform}} ") ]]
         then
           echo "Provide the proper platforms listed here [ ${valid_platform[*]} ]" 
           exit 1
         fi
         
+   #-----------------------------------------Checking component and tag --------------------------------------------------     
+   
         if [[ !(" ${valid_versions[*]} " =~ " ${{inputs.currentversion}} ") ]]
         then
           echo "Invalid Major version ${{inputs.currentversion}}" 
@@ -93,4 +97,10 @@ runs:
               fi 
             done 
           fi
+     #-----------------------------------------checking app version--------------------------------------------------     
+        if [[ !(" ${{ inputs.validversion}} " =~ " ${{ inputs.app_version }} ") ]]
+        then
+          echo "Invalid Major version ${{ inputs.currentversion }}"
+          exit 1
+        fi
       shell: bash
