Update action.yaml

diff --git a/image-deployment/actions/promotion-inputvalidation/action.yaml b/image-deployment/actions/promotion-inputvalidation/action.yaml
--- a/image-deployment/actions/promotion-inputvalidation/action.yaml
+++ b/image-deployment/actions/promotion-inputvalidation/action.yaml
@@ -36,4 +36,12 @@ runs:
         fi
               components=($(echo ${{ inputs.component }} | sed -e 's\,\ \g'))
            tags=($(echo ${{ inputs.tag }} | sed -e 's\,\ \g'))
+          for cldp_component in ${!components[@]}
+         do
+          if [[ ! (" ${valid_components[*]} " =~ " ${components[$cldp_component]}: ${tags[$cldp_component]} ") ]]
+          then
+            echo " ${components[$cldp_component]}: ${tags[$cldp_component]} not found"
+            exit 1 
+          fi 
+         done 
       shell: bash
